# 数据库类型选择: sqlite3 或 mysql
database_type: sqlite3

sqlite3:
  file: /Users/yaodao/devTools/sqlite/sqlite.db
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: blog
apikey: rss_api_secret_key
website:
  url: your_website_url
  title: your_website_title
  description: your_website_description
  follow_feed_id: follow_feed_id_for_claim
  follow_user_id: follow_user_id_for_claim

auth:
  admin_password: "$2a$10$Rwkf8ripNXuClGo8FjfXnuU0WqhRxHMGsmTg9WavCRw0d0V7YRe7G"
  jwt_secret: "a_very_secret_and_long_key_that_should_be_changed"

github:
  token: ""