sqlite3:
  file: /Users/yaodao/devTools/sqlite/sqlite.db
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
apikey: rss_api_secret_key
website:
  url: your_website_url
  title: your_website_title
  description: your_website_description
  follow_feed_id: follow_feed_id_for_claim
  follow_user_id: follow_user_id_for_claim